name: LoginSystem
version: '${project.version}'
main: dev.wonkypigs.loginsystem.LoginSystem
api-version: 1.19
authors: [ WonkyPigs ]
description: A simple plugin which adds a login password system for players
commands:
  login:
    description: The command used to log in the server
    usage: /login <password>
  setpassword:
    description: The command used to set a password for a player
    usage: /setpassword <password>
    aliases:
      - setpass
      - sp
  changepassword:
    description: The command used to change a password for a player
    usage: /changepassword <password>
    aliases:
      - changepass
      - cp